---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/backend
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/