name : "agency-backend"

services:
  database:
    image: "mariadb:11"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3308:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: agency

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules

    depends_on:
      database:
        condition: service_healthy
